#   Login PMO
POST http://localhost:8000/accounts/login/ HTTP/1.1
content-type: application/json

{
    "email": "pmo@email.com",
    "password": "pmo12345"
}

# {
#     "email": "admin@email.com",
#     "password": "admin"
# }

### Login PS
POST http://localhost:8000/accounts/login/ HTTP/1.1
content-type: application/json

{
    "email": "ps@email.com",
    "password": "ps123456"
}

###   Log out
POST http://localhost:8000/accounts/logout/ HTTP/1.1
Authorization: token d833698d124efab46f1e464900254968cf34e58bbc55a3bcfa027620720b4385


###   Register PMO
POST http://localhost:8000/accounts/register/ HTTP/1.1
content-type: application/json

{
    "first_name": "Luca",
    "last_name": "Verdi",
    "email": "pmo@email.com",
    "password": "pmo12345",
    "confirm_password": "pmo12345",
    "user_type": "PMO"
}


### Register PS
POST http://localhost:8000/accounts/register/ HTTP/1.1
content-type: application/json

{
    "first_name": "Giovanni",
    "last_name": "Valdieri",
    "email": "ps@email.com",
    "password": "ps123456",
    "confirm_password": "ps123456",
    "user_type": "PS"
}


### Activate user
### permissions: IsAuthenticated, IsPMO
PATCH  http://localhost:8000/accounts/activateuser/3/ HTTP/1.1
Authorization: token c42cd7af51ae1fbc0c1d5b1875f271786d67a8204a5b42c46cc2c0775c5e8754


### Deactivate user
### permissions: IsAuthenticated, IsPMO
PATCH  http://localhost:8000/accounts/deactivateuser/3/ HTTP/1.1
Authorization: token c42cd7af51ae1fbc0c1d5b1875f271786d67a8204a5b42c46cc2c0775c5e8754


### GET single user instance
### permissions: IsAuthenticated, IsOwnerOrPMO
GET  http://localhost:8000/accounts/2/ HTTP/1.1
Authorization: token 8cabf3c044a93ecbe9e6812440fd7bdfced54f49be36a3225f96026622424d9b


### GET user list
### permissions: IsAuthenticated, IsPMO
GET  http://localhost:8000/accounts/ HTTP/1.1
Authorization: token c42cd7af51ae1fbc0c1d5b1875f271786d67a8204a5b42c46cc2c0775c5e8754
