# Generated by Django 4.0.3 on 2022-04-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_charter', '0004_alter_businesscaseswot_options_and_more'),
        ('project_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbudget',
            name='project_charter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_budget', to='project_charter.projectcharter'),
        ),
    ]
