# Generated by Django 4.0.3 on 2022-05-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('project_procurements', '0002_alter_contract_project'),
        ('project_budget', '0003_contractspendings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractSpendings',
            new_name='ContractSpending',
        ),
    ]
