# Generated by Django 4.0.3 on 2022-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0005_alter_contractspending_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespending',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'approved'), ('denied', 'denied')], default='approved', max_length=9),
        ),
    ]
