# Generated by Django 4.0.3 on 2022-05-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0006_resourcespending_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespending',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'approved'), ('denied', 'denied')], default='denied', max_length=9),
        ),
    ]
