# Generated by Django 4.0.3 on 2022-05-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_resources', '0001_initial'),
        ('projects', '0001_initial'),
        ('project_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespending',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_budget.projectbudget'),
        ),
        migrations.AlterField(
            model_name='resourcespending',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='resourcespending',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_resources.resource'),
        ),
    ]
