# Generated by Django 4.0.3 on 2022-06-18 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractspending',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resourcespending',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
