# Generated by Django 4.0.3 on 2022-05-15 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_procurements', '0002_alter_contract_project'),
        ('projects', '0001_initial'),
        ('project_budget', '0002_alter_resourcespending_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSpendings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('date', models.DateField(default=datetime.date(2022, 5, 15))),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_budget.projectbudget')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_procurements.contract')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ('project', 'budget'),
            },
        ),
    ]
