# Generated by Django 4.0.3 on 2022-06-18 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0003_alter_additionalbudget_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalbudget',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='additionalbudget',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('denied', 'denied')], default='waiting', max_length=8),
        ),
    ]
