# Generated by Django 4.0.3 on 2022-05-20 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0004_rename_contractspendings_contractspending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractspending',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 20)),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resourcespending',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 20)),
        ),
    ]
