# Generated by Django 4.0.3 on 2022-06-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0004_alter_additionalbudget_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalbudget',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contractspending',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resourcespending',
            name='date',
            field=models.DateField(),
        ),
    ]
