# Generated by Django 4.0.3 on 2022-05-21 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_budget', '0009_alter_contractspending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractspending',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 22)),
        ),
        migrations.AlterField(
            model_name='resourcespending',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 22)),
        ),
    ]
