# Generated by Django 4.0.3 on 2022-05-15 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sow', models.CharField(blank=True, max_length=1024, null=True)),
                ('contract', models.CharField(blank=True, max_length=1024, null=True)),
                ('business_case', models.CharField(blank=True, max_length=1024, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_charter', to='projects.project')),
            ],
            options={
                'ordering': ('project',),
            },
        ),
        migrations.CreateModel(
            name='BusinessCaseSWOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swot_type', models.CharField(choices=[('strength', 'strength'), ('weakness', 'weakness'), ('opportunity', 'opportunity'), ('threat', 'threat')], max_length=11)),
                ('content', models.CharField(blank=True, max_length=1024)),
                ('project_charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_case_swot', to='project_charter.projectcharter')),
            ],
            options={
                'ordering': ('project_charter',),
            },
        ),
    ]
