# Generated by Django 4.0.3 on 2022-05-15 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('unit_price', models.FloatField(default=0)),
                ('assignment', models.IntegerField(default=0)),
                ('supplier', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2022, 5, 15))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contract', to='projects.project')),
            ],
            options={
                'ordering': ('project', 'date'),
            },
        ),
    ]
