# Generated by Django 4.0.3 on 2022-05-21 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_procurements', '0004_contract_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
    ]
