# Generated by Django 4.0.3 on 2022-05-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(default=None, max_length=1024),
        ),
    ]
