# Generated by Django 4.0.3 on 2022-06-18 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='stakeholders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('project_name',),
                'permissions': (('add_project_charter', 'Can add project charter /to project charter'), ('change_project_charter', 'Can change project charter'), ('delete_project_charter', 'Can delete project charter'), ('view_project_charter', 'Can view project charter'), ('add_project_resource', 'Can add project resource'), ('change_project_resource', 'Can change project resource'), ('delete_project_resource', 'Can delete project resource'), ('view_project_resource', 'Can view project resource'), ('add_project_contract', 'Can add project contract'), ('change_project_contract', 'Can change project contract'), ('delete_project_contract', 'Can delete project contract'), ('view_project_contract', 'Can view project contract'), ('add_project_spendings', 'Can add project spendings'), ('change_project_spendings', 'Can change project spendings'), ('delete_project_spendings', 'Can delete project spendings'), ('view_project_spendings', 'Can view project spendings')),
            },
        ),
    ]
