# Generated by Django 4.0.3 on 2022-05-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(default='euro', max_length=255),
        ),
    ]
