# Generated by Django 4.0.3 on 2022-04-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_charter', '0002_alter_projectcharter_business_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCaseSWOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swot_type', models.CharField(choices=[('strength', 'strength'), ('weakness', 'weakness'), ('opportunity', 'opportunity'), ('threat', 'threat')], max_length=11)),
                ('content', models.CharField(blank=True, max_length=1024)),
                ('project_charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_charter.projectcharter')),
            ],
            options={
                'ordering': ('content',),
            },
        ),
    ]
