# Generated by Django 4.0.3 on 2022-04-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_oa'),
        ('project_charter', '0003_businesscaseswot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscaseswot',
            options={'ordering': ('project_charter',)},
        ),
        migrations.AlterField(
            model_name='businesscaseswot',
            name='project_charter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_case_swot', to='project_charter.projectcharter'),
        ),
        migrations.AlterField(
            model_name='projectcharter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_charter', to='project.project'),
        ),
    ]
