# Generated by Django 4.0.3 on 2022-05-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_options'),
        ('project_charter', '0004_alter_businesscaseswot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcharter',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_charter', to='project.project'),
        ),
    ]
