# Generated by Django 4.0.3 on 2022-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_created_at_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='oa',
            field=models.CharField(default='', max_length=255),
        ),
    ]
