# Generated by Django 4.0.3 on 2022-05-07 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_project_stakeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='stakeholders', to=settings.AUTH_USER_MODEL),
        ),
    ]
