# Generated by Django 4.0.3 on 2022-05-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_stakeholders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('project_name',), 'permissions': (('add_project_charter', 'Can add project charter / to project charter'), ('change_project_charter', 'Can change project charter'), ('delete_project_charter', 'Can delete project charter'), ('view_project_charter', 'Can view project charter'), ('add_project_resource', 'Can add project resource'), ('change_project_resource', 'Can change project resource'), ('delete_project_resource', 'Can delete project resource'), ('view_project_resource', 'Can view project resource'))},
        ),
    ]
