# Generated by Django 4.0.3 on 2022-05-20 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_procurements', '0002_alter_contract_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 20)),
        ),
    ]
