# Generated by Django 4.0.3 on 2022-06-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_procurements', '0003_alter_contract_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(),
        ),
    ]
